"""Screening configuration for Ten Bagger Daily."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content"
DAILY_DIR = CONTENT_DIR / "daily"
MANIFEST_PATH = CONTENT_DIR / "manifest.json"
UNIVERSE_DIR = Path(__file__).resolve().parent / "universe"
SCHEMA_PATH = Path(__file__).resolve().parent / "schema" / "daily-entry.schema.json"
CACHE_DIR = Path(__file__).resolve().parent / "cache"
CACHE_TTL_SECONDS = 43_200  # 12 hours

SCORE_VERSION = 2
COMPOSITE_THRESHOLD = 70.0
DUPLICATE_BAN_DAYS = 30
SCREEN_WORKERS = 2

# Minimum market cap for pre-screen (when cap data is available).
MIN_MARKET_CAP_KR = 50_000_000_000  # 500억 KRW
MIN_MARKET_CAP_US = 300_000_000  # $300M USD

# Size scoring — ideal cap band for max score (Epic #17)
MAX_IDEAL_MARKET_CAP_KR = 2_000_000_000_000  # 2조 KRW
MAX_IDEAL_MARKET_CAP_US = 2_000_000_000  # $2B USD
ANALYST_LOW_COVERAGE_MAX = 5
ANALYST_COVERAGE_BONUS = 8.0

# yfinance fetch resilience
YF_MAX_RETRIES = 5
YF_RETRY_BASE_DELAY = 2.0  # seconds, exponential backoff
YF_RATE_LIMIT_DELAY = 30.0  # extra pause when Yahoo returns 429
YF_MIN_REQUEST_INTERVAL = 0.35  # global throttle between live API calls

# Score v2 weights (Epic #22)
WEIGHT_SIZE = 0.15
WEIGHT_VALUATION = 0.25
WEIGHT_GROWTH = 0.20
WEIGHT_QUALITY = 0.20
WEIGHT_ENTRY = 0.10
WEIGHT_MOMENTUM = 0.10

# Score v1 weights (backtest comparison)
V1_WEIGHT_GROWTH = 0.40
V1_WEIGHT_VALUATION = 0.30
V1_WEIGHT_MOMENTUM = 0.20
V1_WEIGHT_QUALITY = 0.10

# Growth scoring — sustainable band (Epic #19)
GROWTH_REV_WEIGHT = 0.55
GROWTH_EARN_WEIGHT = 0.45
GROWTH_SWEET_LOW = 20.0
GROWTH_SWEET_HIGH = 50.0
GROWTH_SWEET_PEAK = 30.0
GROWTH_PENALTY_ABOVE = 50.0
GROWTH_BASE_SCORE = 20.0
GROWTH_SCORE_MULTIPLIER = 2.2  # v1 legacy
MAX_GROWTH_PCT = 100.0  # clip yfinance spikes

# Valuation (P/E tiers)
PE_TIER_EXCELLENT = 12
PE_TIER_GOOD = 20
PE_TIER_FAIR = 35
PE_SCORE_EXCELLENT = 85
PE_SCORE_GOOD = 70
PE_SCORE_FAIR = 50
PE_SCORE_POOR = 30
PE_BLEND_WEIGHT = 0.55

PEG_TIER_EXCELLENT = 0.8
PEG_TIER_GOOD = 1.2
PEG_TIER_FAIR = 2.0
PEG_SCORE_EXCELLENT = 90
PEG_SCORE_GOOD = 75
PEG_SCORE_FAIR = 55
PEG_SCORE_POOR = 35
PEG_BLEND_WEIGHT = 0.45

# Valuation v2 blend (Epic #18)
VAL_PE_PEG_WEIGHT = 0.40
VAL_FCF_WEIGHT = 0.35
VAL_PB_WEIGHT = 0.25

FCF_YIELD_EXCELLENT = 8.0
FCF_YIELD_GOOD = 5.0
FCF_YIELD_FAIR = 3.0
FCF_YIELD_POOR = 1.0
FCF_SCORE_EXCELLENT = 95
FCF_SCORE_GOOD = 85
FCF_SCORE_FAIR = 70
FCF_SCORE_POOR = 50
FCF_SCORE_NEGATIVE = 20

BM_EXCELLENT = 0.40
BM_GOOD = 0.25
BM_FAIR = 0.15
BM_SCORE_EXCELLENT = 90
BM_SCORE_GOOD = 75
BM_SCORE_FAIR = 60
BM_SCORE_POOR = 40

# Momentum (v2 dampened; 6M return only — 52W position moved to Entry)
MOMENTUM_MIN_HISTORY_DAYS = 30
MOMENTUM_LOOKBACK_DAYS = 126  # ~6 months
MOMENTUM_DEFAULT_SCORE = 40.0
MOMENTUM_RET_BASE = 35.0
MOMENTUM_RET_MULTIPLIER = 0.8
MOMENTUM_RET_WEIGHT = 0.6
MOMENTUM_HIGH_WEIGHT = 0.4
MOMENTUM_DAMPEN_WEIGHT = 0.65
MOMENTUM_FLOOR = 35.0
MOMENTUM_RECOVERY_LOW = -25
MOMENTUM_RECOVERY_HIGH = -5
MOMENTUM_RECOVERY_SCORE = 75
MOMENTUM_NEAR_HIGH_SCORE = 65
MOMENTUM_DEEP_PULLBACK_SCORE = 45

# Size scoring — leave headroom so analyst bonus can differentiate at ideal cap
SIZE_IDEAL_BASE = 92.0

# Entry timing (Epic #21)
ENTRY_LOOKBACK_DAYS = 252
ENTRY_NEAR_HIGH_PCT = 80.0
ENTRY_MID_HIGH_PCT = 60.0
ENTRY_MID_RANGE_PCT = 30.0
ENTRY_DEFAULT_SCORE = 50.0
ENTRY_RANGE_WEIGHT = 0.70
ENTRY_RECOVERY_WEIGHT = 0.30
ENTRY_NEAR_HIGH_SCORE = 35.0
ENTRY_MID_HIGH_SCORE = 50.0
ENTRY_MID_RANGE_SCORE = 75.0
ENTRY_NEAR_LOW_SCORE = 65.0
ENTRY_AT_HIGH_RECOVERY_SCORE = 40.0

# Quality
QUALITY_ROE_MULTIPLIER = 2.5
QUALITY_ROE_DEFAULT = 30
QUALITY_ROE_WEIGHT = 0.35
QUALITY_DEBT_WEIGHT = 0.20
QUALITY_MARGIN_WEIGHT = 0.25
QUALITY_FCF_NI_WEIGHT = 0.10
QUALITY_ROA_WEIGHT = 0.10
V1_QUALITY_ROE_WEIGHT = 0.45
V1_QUALITY_DEBT_WEIGHT = 0.25
V1_QUALITY_MARGIN_WEIGHT = 0.30
QUALITY_DEBT_EXCELLENT = 50
QUALITY_DEBT_GOOD = 100
QUALITY_DEBT_FAIR = 200
QUALITY_DEBT_SCORE_EXCELLENT = 85
QUALITY_DEBT_SCORE_GOOD = 70
QUALITY_DEBT_SCORE_FAIR = 50
QUALITY_DEBT_SCORE_POOR = 30
QUALITY_MARGIN_BASE = 30.0
QUALITY_MARGIN_MULTIPLIER = 2.0
QUALITY_FCF_NI_EXCELLENT = 1.0
QUALITY_FCF_NI_GOOD = 0.8
QUALITY_ROA_MULTIPLIER = 250.0


@dataclass(frozen=True)
class UniverseSymbol:
    symbol: str
    name_ko: str
    name_en: str
    exchange: str
    currency: str
    market_cap: int | None = None


def market_for_date(date_str: str) -> str:
    """Odd day -> KR, even day -> US (calendar day in KST context)."""
    day = int(date_str.split("-")[2])
    return "KR" if day % 2 == 1 else "US"
